['Bold','Italic','Underline','Strike','Blockquote','SpecialChar'],
['JustifyLeft','JustifyCenter','JustifyRight','JustifyBlock'],
['Undo','Redo','Find','RemoveFormat','NumberedList','BulletedList','Outdent','Indent','-','Maximize','Scayt','-','Source'],
['Styles','Format','Font','FontSize'],['TextColor','BGColor','Image','Table','HorizontalRule','Smiley','PasteFromWord'],
['Link','Unlink','Anchor'],